server:
  port: 8888
  servlet:
    context-path: /openmldb-featinsight
openmldb:
  zk_cluster: 172.27.231.51:2181
  zk_path: /openmldb
  apiserver: 172.27.231.51:9080
  skip_index_check: false
  username: root
  password:
prophet:
  token_auth_enabled: true
  pdms_uri: http://172.27.128.190:40121/telamon