---
apiVersion: v1
kind: Service
metadata:
  name: openmldb-featinsight
  namespace: prophet
  labels:
    app: openmldb-featinsight
    enable-on-api-gw: "true"
  annotations:
    api-gw-conf: '{"gw-api-confs":[{"listen-paths":"/openmldb-featinsight","enable-auth":false,"stripe-url":true}]}'
spec:
  type: ClusterIP
  selector:
    app: openmldb-featinsight
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openmldb-featinsight
  name: openmldb-featinsight
  namespace: prophet
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openmldb-featinsight
      release: aios
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openmldb-featinsight
        prophet.4paradigm.com/deployment: openmldb-featinsight
        release: aios
      name: openmldb-featinsight
    spec:
      imagePullSecrets:
        - name: docker-secret
      nodeSelector:
        prophet.4paradigm.com/system: "true"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: openmldb-featinsight-configmap
          name: openmldb-featinsight-configmap
      containers:
        - env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: TZ
              value: Asia/Shanghai
          image: harbor.4pd.io/studio/openmldb-featinsight:v0.1.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          name: app
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/application.yml
              name: openmldb-featinsight-configmap
              subPath: application.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: openmldb-featinsight
  name: openmldb-featinsight-configmap
  namespace: prophet
data:
  application.yml: |-
    server:
      port: 80
    openmldb:
      zk_cluster: 172.27.128.190:2185
      zk_path: /openmldb
      apiserver: 172.27.128.190:9080
      skip_index_check: false
      username: root
      password:
    prophet:
      token_auth_enabled: true
      pdms_uri: http://172.27.128.190:40121/telamon