apiVersion: v1
kind: Service
metadata:
  name: openmldb-featinsight
  namespace: prophet
  labels:
    app: openmldb-featinsight
    enable-on-api-gw: "true"
  annotations:
    api-gw-conf: '{"gw-api-confs":[{"listen-paths":"/openmldb-featinsight","enable-auth":false}]}'
spec:
  type: ClusterIP
  selector:
    app: openmldb-featinsight
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80