name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  featinsight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: install yarn
        run: |
          npm install -g yarn

      - name: build frontend
        run: |
          yarn
          yarn build
        working-directory: frontend

      - name: build backend
        run: |
          mvn clean compile

      - name: package
        run: |
          mvn package

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feat-insight-jar
          path: |
            target/featinsight-*.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            target/featinsight-*.jar
